version: '3.3'
services:
    couchdb:
        container_name: couchdb
        ports:
            - '5984:5984'
        restart: always
        volumes:
            - './couchdb/data:/opt/couchdb/data'
            - './couchdb/etc:/opt/couchdb/etc/local.d'
        environment:
            - COUCHDB_USER=pan_mats
            - COUCHDB_PASSWORD=panos12345
        image: 'apache/couchdb:latest'
    rabbitmq:
            container_name: rabbitmq
            environment:
                - 'RABBITMQ_ERLANG_COOKIE=iotech-collector'
                - 'RABBITMQ_NODENAME=rabbitmq'
            volumes:
                - './rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config'
                - './rabbitmq/definitions.json:/etc/rabbitmq/definitions.json'
            ports:
                - '4369:4369'
                - '5671:5671'
                - '5672:5672'
                - '15671:15671'
                - '15672:15672'
                - '25672:25672'
            image: 'rabbitmq:3-management'
    parser:
            container_name: nodejs-parser
            image: 